In [2]:
import torch

x=torch.empty(1) #1D 
print(x)

y=torch.empty(2,3) #2D
print(y)

z=torch.zeros(5) 
print(z)

a=torch.ones(4,4)
print(a)

tensor([-9.5170e+21])
tensor([[-9.5170e+21,  4.5713e-41, -5.7350e+26],
        [ 3.0921e-41,  4.4842e-44,  0.0000e+00]])
tensor([0., 0., 0., 0., 0.])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
